# NO empty line between commands
add_newline = false

# Single line prompt (Cleaner)
[line_break]
disabled = true

# The arrow symbol
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

# Hide username unless SSH
[username]
show_always = false

# Shorten directory paths
[directory]
truncation_length = 3
truncation_symbol = "…/"

# Clean Git symbols
[git_branch]
symbol = " "
